### PR TITLE
Revamp Preferences UI.

### PR DESCRIPTION
**Pull request by glerroo**
I want to propose some change to the preferences UI, to make it more coherent in the different Gnome version, and from gnome 42 make use of Adwaita widget.
Gnome >= 42 - Adw1
Current UI
Wireless-HID-Prefs-GS42
New UI
Wireless-HID-Prefs-GS42_new

Gnome >= 40 - Gtk4
Current UI
Wireless-HID_Prefs_GS41
New UI
Wireless-HID_Prefs_GS41_new

Gnome < 40 - Gtk3
Current UI
Wireless_HID-Prefs-GS3 38
New UI
Wireless_HID-Prefs-GS3 38_new

If like merge it.

### CODE REVIEW

**Comment by vchlum** [comment]
Hi @glerroo , thank you for this. Unfortunately, the previous PR caused conflicts. Could you please resolve the conflicts?

**Comment by glerroo** [comment]
Hi @vchlum, yes i can. Thanks you for the extension.

**Comment by glerroo** [comment]
Hi @vchlum, i have resolved the conflicts.

**Comment by vchlum** [comment]
Merged. Thank you for your contribution!

**Pull request merged**
