### PR TITLE
GNOME 45 porting

### PR DESCRIPTION
**Pull request by stuarthayhurst**
Self-explanatory, this ports the extension to GNOME 45.

Due to upstream changes, extensions can't target GNOME 45 at the same time as older versions, so this PR also drops all currently supported version, including all workarounds and previous interfaces
 - On the plus side, the extension is much lighter now

The extension loads and the preferences work, but I did my testing in a VM rather than a bare-metal machine, so I couldn't actually test any devices. As soon as I can test actual devices, I'll post an update on this PR.

If device testing goes smoothly, I'm happy with this, so feel free to review it :)

### CODE REVIEW

**Comment by vchlum** [comment]
Hi! I should have a BT dongle on Monday. I should be able to connect it to VM a test it in VM. Thank you.

**Comment by stuarthayhurst** [comment]
Changed the name of the class exported from `prefs.js`, as they don't like generic class names upstream. Found that one out from a review of one of my own extensions, whoops.

**Comment by vchlum** [comment]
Tested with BT dongle in VM. It works with this patch, please apply:
```
diff --git a/extension/wirelesshid.js b/extension/wirelesshid.js
index 74059f5..03cfa1f 100644
--- a/extension/wirelesshid.js
+++ b/extension/wirelesshid.js
@@ -370,7 +370,7 @@ export var WirelessHID = GObject.registerClass({
     }
 
     newDevice(device) {
-        this._devices[device.native_path] = new HID(device);
+        this._devices[device.native_path] = new HID(device, this._settings);
 
         this._panelBox.add(this._devices[device.native_path].createIcon());
         this.menu.addMenuItem(this._devices[device.native_path].createItem());

```

**Comment by stuarthayhurst** [comment]
Done, thanks

**Pull request merged**
